// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHR2sP1GbYevdC1v6sqRqhk2vs1oms9KM',
    appId: '1:1015856691644:web:97bfe2acf376489e9953b9',
    messagingSenderId: '1015856691644',
    projectId: 'menstrual-health-system',
    authDomain: 'menstrual-health-system.firebaseapp.com',
    storageBucket: 'menstrual-health-system.firebasestorage.app',
    measurementId: 'G-RSQM6009JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrWe_aFVbeOf3igfp8f2W6xW-q2W_vGaU',
    appId: '1:1015856691644:android:8f6d3f61876c45869953b9',
    messagingSenderId: '1015856691644',
    projectId: 'menstrual-health-system',
    storageBucket: 'menstrual-health-system.firebasestorage.app',
  );
}
